{{/*
SPDX-FileCopyrightText: Copyright (C) 2022-2026 Cosmo Tech
SPDX-License-Identifier: MIT
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmotech-gateway.identitySecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "cosmotech-gateway.labels" . | nindent 4 }}
  annotations:
    email: "platform@cosmotech.com"
type: Opaque
stringData:
  clientSecret: {{ .Values.config.csm.platform.gateway.identityProvider.identity.clientSecret | quote }}
