{{/*
SPDX-FileCopyrightText: Copyright (C) 2022-2026 Cosmo Tech
SPDX-License-Identifier: MIT
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cosmotech-kubernetes-backup.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  backup-map-namespace: {{ .Release.Namespace | quote }}
  storage-address: changeme
  storage-username: changeme
  storage-password: changeme