version = 1

[[annotations]]
path = [
  "charts/*/README.md",
  "charts/cosmotech-api/media/schema.png",
]
SPDX-FileCopyrightText = "Copyright (C) 2022-2025 Cosmo Tech"
SPDX-License-Identifier = "MIT"
