{{- if .Values.ingress.enabled -}}
{{- $fullName := include "cosmotech-asset-investment-planning-api.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cosmotech-asset-investment-planning-api.labels" . | nindent 4 }}
  annotations:
    {{- /* Check if ANY path in the hosts list is not "/" to enable regex
       This prevents the need for a global $rootUri variable
    */ -}}
    {{- $useRegex := false -}}
    {{- range .Values.ingress.hosts -}}
      {{- range .paths -}}
        {{- if ne .path "/" -}}
          {{- $useRegex = true -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
    {{- if $useRegex }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- end}}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.secretName }}
  tls:
    - hosts:
        {{- range .Values.ingress.tls.hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ if ne .path "/" }}{{ .path }}(/|$)(.*){{ else }}{{ .path }}{{ end }}
            {{- if (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType | default $.Values.ingress.pathType | default "ImplementationSpecific" }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
