{{/*
SPDX-FileCopyrightText: Copyright (C) 2022-2026 Cosmo Tech
SPDX-License-Identifier: MIT
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  root_uri: {{ .Values.apiConfig.rootUri | b64enc }}
  keycloak: {{ .Values.apiConfig.keycloakRealm | b64enc }}
{{- if .Values.postgres.enabled }}
  postgres-password: {{ .Values.postgres.password | b64enc }}
{{- end }}
