# SPDX-FileCopyrightText: Copyright (C) 2023-2024 Cosmo Tech
# SPDX-License-Identifier: LicenseRef-CosmoTech
nameOverride: cosmotech-modeling-api
fullNameOverride: ""

image:
  repository: ghcr.io/cosmo-tech/cosmotech-modeling-api
  tag: "latest"
  pullPolicy: Always
  credentials:
    pullSecret: ""
    registry: ""
    username: ""
    password: ""

service:
  type: ClusterIP
  port: 8080

serviceMonitor:
  enabled: true
  namespace: cosmotech-monitoring
  port: 9100

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: "1"
    memory: 256Mi
  requests:
    cpu: "1"
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  # -- Enable the data storage persistence
  enabled: true
  # -- PVC size request
  size: 8Gi
  # -- PVC storage class
  storageClass: ""

extraEnv:
  env: []
  envFrom: []

simulatorRegistryCredentials:
  registry: ""
  username: ""
  password: ""

config: {}
