{{/*
SPDX-FileCopyrightText: Copyright (C) 2022-2025 Cosmo Tech
SPDX-License-Identifier: MIT
*/}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cosmotech-copilot-api.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    cosmotech.com/service: {{ include "cosmotech-copilot-api.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      cosmotech.com/service: {{ include "cosmotech-copilot-api.name" . }}
      {{- include "cosmotech-copilot-api.defaultNetworkPolicy" . | nindent 6 }}
  template:
    metadata:
      labels:
        cosmotech.com/service: {{ include "cosmotech-copilot-api.name" . }}
        {{- include "cosmotech-copilot-api.defaultNetworkPolicy" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "cosmotech-copilot-api.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        envFrom:
          - secretRef:
              name: cosmotech-copilot-api-secret