# SPDX-FileCopyrightText: Copyright (C) 2022-2025 Cosmo Tech
# SPDX-License-Identifier: MIT
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.certManagerClusterIssuer | default "letsencrypt-prod" }}
    email: {{ .Values.ingress.email | default "platform@cosmotech.com" }}
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
    nginx.org/client-max-body-size: "0"
  labels:
    owner: csm-platform
  name: {{ .Values.ingress.name | default (include "cosmotech-copilot-api.fullname" .) }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.ingress.serviceName | default (include "cosmotech-copilot-api.fullname" .) }}
            port:
              number: {{ .Values.service.port | default 80 }}
        {{- $contextPath := include "cosmotech-api.contextPath" . }}
        path: {{ $contextPath }}(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecretName | default "letsencrypt-prod" }}
{{- end }}