{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "cosmotech-asset-data-layer-api.fullname" . }}-strip-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
    {{- range .Values.ingress.hosts }}
      {{- range .paths }}
        - {{ .path }}
      {{- end }}
    {{- end }}
    forceSlash: true
{{- end }}
