apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  root_uri: {{ .Values.apiConfig.rootUri | b64enc }}
{{- if .Values.postgres.enabled }}
  postgres-password: {{ .Values.postgres.password | b64enc }}
{{- end }}
{{- if .Values.seaweedfs.enabled }}
  seaweedfs-secret-key: {{ .Values.seaweedfs.secretKey | b64enc }}
{{- end }}
