# SPDX-FileCopyrightText: Copyright (C) 2022-2025 Cosmo Tech
# SPDX-License-Identifier: MIT
apiVersion: v2
name: cosmotech-modeling-api
description: Cosmo Tech Modeling API
type: application
version: 0.5.0
