# SPDX-FileCopyrightText: Copyright (C) 2022-2026 Cosmo Tech
# SPDX-License-Identifier: MIT

# Override the chart name
nameOverride: ""
fullnameOverride: ""

# Override the default image
image:
  repository: ghcr.io/cosmo-tech/bkup
  pullPolicy: IfNotPresent
  tag: "latest"

# Secret name for pulling the bkup image from a private repository
imagePullSecrets: ""

# Customize workload of master
master:
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

## Customize workload of workers
# worker:
#   tolerations: []
#   affinity: {}
#   resources:
#     limits:
#       cpu: 100m
#       memory: 128Mi
#     requests:
#       cpu: 100m
#       memory: 128Mi

# Backup jobs behaviors
backup:
  # Cron expression to specify when to run the jobs
  cron: ""
  # Number of successful jobs to keep in history
  successfulJobsHistoryLimit: 3
  # Number of failed jobs to keep in history
  failedJobsHistoryLimit: 5

# Required cluster name
clusterName: ""
