{{/*
SPDX-FileCopyrightText: Copyright (C) 2022-2026 Cosmo Tech
SPDX-License-Identifier: MIT
*/}}
{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Values.name }}-strip-webapp-prefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.webapp.publicUrl }}
    forceSlash: true
{{- end }}
