{{/*
SPDX-FileCopyrightText: Copyright (C) 2022-2026 Cosmo Tech
SPDX-License-Identifier: MIT
*/}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ .Values.name }}-strip-webapp-prefix@kubernetescrd
  name: {{ include "cosmotech-business-webapp.server-name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.webapp.domainName }}
    http:
      paths:
      - path: {{ .Values.webapp.publicUrl }}/api
        pathType: Prefix
        backend:
          service:
            name: {{ include "cosmotech-business-webapp.functions-name" . }}
            port:
              number: 8080
      - path: {{ .Values.webapp.publicUrl }}
        pathType: Prefix
        backend:
          service:
            name: {{ include "cosmotech-business-webapp.server-name" . }}
            port:
              number: 8080
  tls:
  - hosts:
    - {{ .Values.webapp.domainName }}
    secretName: letsencrypt-prod
{{- end }}
