# SPDX-FileCopyrightText: Copyright (C) 2023-2024 Cosmo Tech
# SPDX-License-Identifier: LicenseRef-CosmoTech
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cosmotech-modeling-api.fullname" . }}
  labels:
    {{- include "cosmotech-modeling-api.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cosmotech-modeling-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cosmotech-modeling-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.credentials.registry }}
      imagePullSecrets:
        - name: {{ include "cosmotech-modeling-api.fullname" . }}-registry
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: {{ include "cosmotech-modeling-api.fullname" . }}-data-storage
      {{- end }}
      containers:
        - name: cosmotech-modeling-api
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "cosmotech-modeling-api.appVersion" . }}"
          command: ["csm-modeling-server"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9100
              protocol: TCP
          env:
            - name: CSM_BUILDIMAGE_REPOSITORY
              value: {{ .Values.image.repository }}
            - name: CSM_BUILDIMAGE_PULLSECRET
              value: {{ include "cosmotech-modeling-api.fullname" . }}-registry
            - name: CSM_DATA_PATH
              value: {{ include "cosmotech-modeling-api.dataPersistencePath" . }}
            {{- with .Values.config.apiSettings }}
            - name: CSM_COSMOTECHAPI_SETTINGS
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.config.argoSettings }}
            - name: CSM_ARGOWORKFLOWS_SETTINGS
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.config.s3.user }}
            - name: AWS_ACCESS_KEY_ID
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- with .Values.config.s3.password }}
            - name: AWS_SECRET_ACCESS_KEY
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: data-storage
              mountPath: {{ include "cosmotech-modeling-api.dataPersistencePath" . }}
              readOnly: false
          {{- end }}
          resources:
            {{- toYaml .Values.resource | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
