name: Release Charts

on:
  workflow_dispatch:
    inputs:
      chart_name:
        description: "Name of the chart to release"
        required: true
        type: choice
        options:
          - cosmotech-api
          - cosmotech-business-webapp
          - cosmotech-copilot-api
          - cosmotech-modeling-api

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Compute repository name
        run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> "$GITHUB_ENV"

      - name: Install chart releaser
        run: |
          cr_version=1.8.1
          curl -sSL https://github.com/helm/chart-releaser/releases/download/v${cr_version}/chart-releaser_${cr_version}_linux_amd64.tar.gz -o cr.tgz
          mkdir cr_bin
          tar -xzf cr.tgz -C cr_bin
          rm cr.tgz
          echo "$PWD/cr_bin" >> "$GITHUB_PATH"

      - name: Chart package
        run: |
          cr package ${{ inputs.chart_name }}

      - name: Chart release
        run: >
          cr upload
            --owner ${{ github.repository_owner }}
            --git-repo ${{ env.REPO_NAME }}
            --token ${{ secrets.GITHUB_TOKEN }}
            --commit ${{ github.sha }}

      - name: Index update
        run: >
          cr index
            --owner ${{ github.repository_owner }}
            --git-repo ${{ env.REPO_NAME }}
            --token ${{ secrets.GITHUB_TOKEN }}
            --push
