# SPDX-FileCopyrightText: Copyright (C) 2023-2024 Cosmo Tech
# SPDX-License-Identifier: LicenseRef-CosmoTech
name: Restart deployments

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "Docker image tag that was updated"
        required: true
        type: string

jobs:
  restart:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/login@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      - uses: azure/aks-set-context@v3.2
        with:
          cluster-name: "${{ vars.CLUSTER_NAME }}"
          resource-group: "${{ vars.CLUSTER_RESOURCE_GROUP }}"

      - name: Check cluster availability
        id: cluster_availability
        continue-on-error: true
        run: |
          kubectl version

      - name: Restart deployment
        if: ${{ steps.cluster_availability.outcome == 'success' }}
        run: |
          kubectl rollout restart \
            --namespace ${{ vars.CLUSTER_NAMESPACE }} \
            deployment/cosmotech-modeling-api-${{ inputs.imageTag }}

      - name: Wait for restart to finish
        if: ${{ steps.cluster_availability.outcome == 'success' }}
        run: |
          kubectl rollout status \
            --namespace ${{ vars.CLUSTER_NAMESPACE }} \
            --timeout=10m \
            deployment/cosmotech-modeling-api-${{ inputs.imageTag }}
